baseURL: "https://gilbertdev.net"
languageCode: "en-us"
title: "Nicholas Gilbert Blog"
theme: 'papermod'

menu:
  main:
    - name: Archive
      url: archives
      weight: 5
    - name: Projects
      url: projects/
      weight: 10
    - name: Tags
      url: tags/
      weight: 10

taxonomies:
  category: categories
  tag: tags

params:
  env: production
  description: "Portfolio for my work and also blog for my thoughts"
  author: Nicholas Gilbert

  homeInfoParams:
    Title: Hello there!
    Content: My name is Nicholas Gilbert, welcome to my blog / portfolio! Still a work a progress, but have a look around! Click some links!
    assets:
      favicon: "/favicon.ico"
      favicon16x16:  "/favicon-16x16.png"
      favicon32x32:  "/favicon-32x32.png"
      apple_touch_icon:  "/apple-touch-icon.png"
      safari_pinned_tab:  "/safari-pinned-tab.svg"

  socialIcons:
        - name: github
          url: "http://github.gilbertdev.net"
        - name: gitlab
          url: "http://gitlab.gilbertdev.net"
        - name: LinkedIn
          url: "http://linkedin.gilbertdev.net"