baseURL: "https://gilbertdev.net"
languageCode: "en-us"
title: "Nicholas Gilbert-Croysdale Blog"
theme: 'papermod'
paginate: 5

menu:
  main:
    #- name: About Me
    #  url: /about/
    #  weight: 4
    - name: Projects
      url: /projects/
      weight: 5
    - name: Archive
      url: /archives/
      weight: 6
    - name: Tags
      url: /tags/
      weight: 7
    - Name: Repository
      url: https://github.com/gilben1/gilben1.github.io
      weight: 8

taxonomies:
  category: categories
  tag: tags

params:
  env: production
  description: "Portfolio for my work and also blog for my thoughts"
  author: Nicholas Gilbert-Croysdale
  comments: true

  homeInfoParams:
    Title: Hello there!
    Content: |
      My name is Nicholas Gilbert-Croysdale, welcome to my blog / portfolio! I'm a Senior Systems Engineer who specializes in automation using Powershell to yell at Azure / Azure adjacent things.
      
      -

      This site is still a work a progress, but feel free to have a look around!
      
      -

      Read some of my ramblings about making this blog and other tech-adjacent topics, or check out some of the old projects I've worked on.

  socialIcons:
        - name: github
          url: "http://github.gilbertdev.net"
        - name: gitlab
          url: "http://gitlab.gilbertdev.net"
        - name: LinkedIn
          url: "http://linkedin.gilbertdev.net"
  ShowPostNavLinks: true
  ShowToc: true
  TocOpen: false
  ShowReadingTime: true

  giscus:
    repo: gilben1/gilben1.github.io
    repoID: MDEwOlJlcG9zaXRvcnkyNDY0MjI1NjU=
    category: Announcements
    categoryID: DIC_kwDODrAcJc4CUA9K
    mapping: url
    inputPosition: top
    theme: transparent_dark
    lang: en